"""Writes packs-dnm.js from tools/dnm-sources.lock.json: every D&M pack file with
the credit read from its own source page by tools/sounds.py."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lock = json.load(open(os.path.join(ROOT, "tools", "dnm-sources.lock.json")))
VOL = {"sfx": 1, "amb": 0.6}
lines = []
for f in lock:
    lic = "CC BY" if f["license"].startswith("CC BY") else f["license"]
    credit = {"author": f["author"], "title": f["title"], "url": f["url"], "license": lic,
              "licenseUrl": f["licenseUrl"], "changes": f["changes"]}
    s = {"name": f["name"], "page": f["page"], "file": f["out"], "credit": credit}
    if f["out"].startswith("amb/"):
        s["vol"] = VOL["amb"]
    lines.append("  " + json.dumps(s, ensure_ascii=False) + ",")
out = f"""// =============================================================
// packs-dnm.js — GENERATED by tools/lock-to-js.py. Do not edit by hand.
// -------------------------------------------------------------
// The Dreams & Machines pack's files, each with the credit tools/sounds.py read
// from the file's own page (Freesound) or zip (Kenney), and what was done to it.
// To change a file, change tools/dnm-sources.json and run both tools again.
// =============================================================
export const DNM_SOUNDS = [
{chr(10).join(lines)}
];
"""
open(os.path.join(ROOT, "packs-dnm.js"), "w").write(out)
print(len(lock), "sounds written to packs-dnm.js")
